from app.services.todosService import TODOS

LISTS = [
    {
        'id':0,
        'todos':[
            {
                'id':0,
                'task':{
                    'name':'Eat',
                    'created_on':'29/02/2020'
                }
            },
            {
                'id':1,
                'task':{
                    'name':'Sleep',
                    'created_on':'01/03/2020'
                }
            },
            {
                'id':2,
                'task':{
                    'name':'Code',
                    'created_on':'02/03/2020'
                }
            },
            {
                'id':3,
                'task':{
                    'name':'Compile (but compiling is doubting)',
                    'created_on':'02/03/2020'
                }
            },
            {
                'id':4,
                'task':{
                    'name':'Rfrom app.services.todosService import TODOSepeat',
                    'created_on':'03/03/2020'
                }
            }
        ]
        },
        {
            'id':1,
            'todos':[
                {
                    'id':0,
                    'task':{
                        'name':'Eat',
                        'created_on':'29/02/2020'
                    }
                    },
                    {
                        'id':1,
                        'task':{
                            'name':'Sleep',
                            'created_on':'01/03/2020'
                        }
                    },
                    {
                        'id':2,
                        'task':{
                            'name':'Code',
                            'created_on':'02/03/2020'
                        }
                    }
            ]
        }
]