version: '3'
services:
  api-service:
    build: .
    container_name : myFlaskAPI
    volumes:
      - ./:/app/
    ports:
      - 5000:5000
    environment: 
      PORT: 5000
      FLASK_DEBUG: 1
    restart: always